apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: podinfod
          resources:
            limits:
              cpu: 512m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi