apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# images:
#   - name: cc-epg-service
#     newName: UPDATED_BY_CIRCLECI
#     newTag: UPDATED_BY_CIRCLECI

bases:
  - ../../base

# configMapGenerator:
#   - name: cc-epg-service
#     behavior: merge
#     literals:
#       - AUTH_ISSUER="https://auth.staging.bewatec.com/"
#       - AUTH_JWKS_URI="https://auth.staging.bewatec.com/.well-known/jwks.json"
#       - AUTH_AUDIENCE="https://stg-epg.bewatec.com"
#       - AWS_S3_BUCKET_NAME="bewatec-sky-epg"

patchesStrategicMerge:
  - deployment.yaml

# resources:
#   - sealed-secrets.yaml